# This is the main config file for Jimce

# All options regarding the webserver
server:
  port: 8080

# All options regarding the PostgreSQL database (must be compliant with the db setup)
database:
  user: jimce
  password: jimce
  db: jimce
  port: 5432
  host: localhost

# Authentication
auth:
  jwt_secret: dev-secret-CHANGE-IN-PROD!

# Metadata providers
# For now let's use this minimal setup:
metadata:
  providers:
    deezer: {} # empty braces to enable a provider without providing extra configuration / options
    youtube: {}
  flows:
    preferred: # Preferred flows will all be queried at the same time
      # auto lets Jimce pick the best configured provider for the job (does not work for search)
      # in this case both preferred and fallback flow should be identical
      - [deezer, auto, auto] # schema: [search, metadata, sound]
    fallback: # Fallback flows will be queried sequentially if all preferred flows fail to a large extent
      - [deezer, deezer, youtube]
